#!/usr/bin/python
import sys
from urllib import unquote

username = sys.argv[1]
username = unquote(username).decode('utf8')

if username.endswith('@oa4mp.xsede.org'):
  username = username[:-16]

print(username)
